# Generated by Django 4.1.6 on 2023-04-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featutred_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featutred_image',
            new_name='featured_image',
        ),
    ]
